# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  FQDN: "backstage.192.168.49.2.nip.io"
  NS: "backstage"

tasks:
  certs:
    cmds:
      - mkcert {{ .FQDN }}
      - mkcert -install
      - kubectl create ns {{ .NS }}
      - kubectl -n {{ .NS }} create secret tls cert --cert=./{{ .FQDN }}.pem --key=./{{ .FQDN }}-key.pem

  install:
    cmds:
      - helm upgrade -n {{ .NS }} -i backstage backstage/backstage -f values.yml

  delete:
    cmds:
      - helm uninstall -n {{ .NS }} backstage
      - kubectl -n {{ .NS }} delete secret cert
      - kubectl delete ns {{ .NS }}
      - mkcert -uninstall

  full:
    cmds:
      - task: certs
      - task: install
