# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
# mc config -> needed for create and restore backup
  set-mc-config:
    internal: true
    vars:
      MINIKUBE_IP:
        sh: minikube ip
    cmds:
      - |
        mc alias set gitlab \
          https://minio.{{ .MINIKUBE_IP }}.nip.io/ \
          $(kubectl get secret gitlab-minio-secret -ojsonpath='{.data.accesskey}' | base64 --decode) \
          $(kubectl get secret gitlab-minio-secret -ojsonpath='{.data.secretkey}' | base64 --decode) \
          --insecure

  configure-gitlab:
    internal: true
    vars:
      MINIKUBE_IP:
        sh: minikube ip
    dir: gitlab/gitlab-config
    cmds:
      - terraform init
      - terraform apply  -var gitlab_token={{ .INIT_TOKEN }} -var minikubeip={{ .MINIKUBE_IP }} -auto-approve

  backup-rails-secret:
    internal: true
    cmds:
      - kubectl get secrets gitlab-rails-secret -o jsonpath="{.data['secrets\.yml']}" | base64 --decode > gitlab-secrets.yml

  create-backup:
    internal: true
    cmds:
      - |
        kubectl exec \
          $(kubectl get pods -lapp=toolbox --field-selector=status.phase=Running -o=name) \
          -it -- \
          backup-utility

  get-backup:
    internal: true
    cmds:
      - mc --insecure cp gitlab/backup/$(mc --insecure ls gitlab/gitlab-backups --json | jq -r .key) .

  # restore backup
  restore-rails-secret:
    internal: true
    cmds:
      - kubectl delete secrets gitlab-rails-secret
      - kubectl create secret generic gitlab-rails-secret --from-file=secrets.yml=gitlab-secrets.yml
      - kubectl delete pods -lapp=sidekiq
      - kubectl delete pods -lapp=webservice
      - kubectl delete pods -lapp=toolbox

  put-backup:
    internal: true
    cmds:
      - mc --insecure cp $(find . -name "*.tar") gitlab/gitlab-backups/

  restore-backup:
    internal: true
    cmds:
      - |
        kubectl exec \
          $(kubectl get pods -lapp=toolbox --field-selector=status.phase=Running -o=name) \
          -it -- \
          backup-utility --restore -t \
          $(mc --insecure ls gitlab/backup/ --json | jq -r .key | sed -e s/_gitlab_backup.tar//)
