apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: gitlab-push-events-trigger
spec:
  interceptors:
    # gitlab-bindings
    - name: "verify-gitlab-payload"
      ref:
        name: "gitlab"
        kind: ClusterInterceptor
      params:
        - name: secretRef
          value:
            secretName: "gitlab-secret"
            secretKey: "secretToken"
        - name: eventTypes
          value:
            - "Push Hook"
            - "Tag Push Hook"
    # gitlab-bindings-custom
    - name: "gitlab-custom-vars"
      ref:
        name: "cel"
      params:
        - name: "overlays"
          value:
            - key: truncated_sha
              expression: "body.checkout_sha.truncate(7)"
            - key: branch_name
              expression: "body.ref.split('/')[2]"
  bindings:
    - ref: gitlab-bindings
    - ref: gitlab-bindings-custom
  template:
    ref: gitlab-repo-print
