# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  backup: ./backup

tasks:
  helm:
    desc: gitlab helm upgrade
    dir: gitlab
    cmds:
      - helm repo add gitlab https://charts.gitlab.io/
      - helm repo update
      - helm upgrade --install gitlab gitlab/gitlab -f values.yml

  fix-ips:
    internal: true
    dir: gitlab
    vars:
      MINIKUBE_IP:
        sh: minikube ip
    cmds:
      - yq -i '.global.hosts.domain = "{{ .MINIKUBE_IP }}.nip.io"' values.yml
      - yq -i '.global.hosts.externalIP = "{{ .MINIKUBE_IP }}"' values.yml
      - cat values.yml

  get-creds:
    desc: get gitlab login credentials
    cmds:
      - 'echo url: $(kubectl get ingress gitlab-webservice-default -ojsonpath="{.spec.rules[0].host}")'
      - 'echo user: root'
      - 'echo pass: $(kubectl get secret gitlab-gitlab-initial-root-password -ojsonpath="{.data.password}" | base64 --decode ; echo)'
    silent: true

  wait-for:
    internal: true
    vars:
      TIMEOUT: 480s
    cmds:
      - kubectl wait --timeout={{ .TIMEOUT }} --for=condition=ready pod -l app=webservice
      - echo "Gitlab is ready!!!"
