name: stack test
on:
  pull_request:
    branches: ["master"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: test gitlab
        uses: "infinite-automations/terraform-all-in-one@bf7348a1b77f91a1bc868e69c62bc840e1a362db" # v1.2.0
        with:
          plan: false
          test: true
          directory: "./gitlab"
          test-directory: "./gitlab"
